### ISSUE TITLE
File <vector> not found when building or running

### ISSUE THREAD

**Issue by Sam-Spencer** [rsms/chromium-tabs#13]
When attempting to build the latest version of the framework on 10.8.2 Xcode can't find a file called "vector" in an #import line. It also can't find the "algorithm" file.

**Comment by SevenBits** [comment]
Did you import the whole project correctly?

**Comment by michaelli611** [comment]
Rename your file to ".mm"

**Comment by sunki** [comment]
same issue. What file should I rename? Mac 10.9.2 Xcode 5.1

**Comment by SevenBits** [comment]
@sunki The file in which the error is triggered. If the error occurs in the file `file.m`, then rename it to `file.mm` and update the project accordingly.

**Comment by sunki** [comment]
@SevenBits tried, not helped. Got a lot of other errors after that

**Comment by SevenBits** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

You may have to modify multiple files. I don't know, though; I'm not
the maintainer of this tool, and unless an update was pushed recently
I believe it has not been worked on in some time.

On 04/03/2014 05:56 PM, sunki wrote:

> tried, not helped. Got a lot of other errors after that
> 
> --- Reply to this email directly or view it on GitHub: 
> https://github.com/rsms/chromium-tabs/issues/13#issuecomment-39510093
> 
> -----BEGIN PGP SIGNATURE-----
> Version: GnuPG v1.4.14 (GNU/Linux)
> Comment: Using GnuPG with Thunderbird - http://www.enigmail.net/

iQEcBAEBAgAGBQJTPd8uAAoJEM44RjRtcVbv4lIIALmKC08IBoiNdIGJqCAcZjlm
XJMPVnQzmmk9aIm8+Nqqre9CIcRNccQm9trseVFItnOg0nbJmHbv/G1583sZ+TaU
DjEf9zL1kOqfVVEwj7fW3XTXbL+/NaNUV8vI8L5XUvUKCPNhlupLiy2NPqTVRXdR
+m7KVjktUdM/rjdPstsLABobioPGuYmmqMBHZ+D3iyOJqKFkf7DmxRwVNuNzFmYM
QYbFMuglvHgPNaqErOonpfmgGCNCBScdg36k5PrM5TVZITShP9qtuUfcre/kOGUl
4ot6W9e7wjOlr5ZekqFiKtkXPGPjobtNN+c+iIKnj6OxShzWDFrxal54Ml6ZeDQ=
=8ZR6
-----END PGP SIGNATURE-----

**Comment by elklein** [comment]
vector and algorithm are STL files. They implicitly require C++. Is there any chance you are compiling your project as not C++ compatible somehow? Something about your project isn't set up to include those files' include paths. xcode does a lot of that automagically, so it's sort of hard to figure out when things don't go wrong, but... that's really the core issue here.

**Comment by sunki** [comment]
I have something similiar to this:
http://stackoverflow.com/questions/8222846/xcode-4-2-suddenly-doesnt-know-anything-about-stl
It worked and then just suddenly stopped. I tried to clean and downgrade Xcode. No luck.

**Comment by elklein** [comment]
That's weird and frustrating. I'm sorry, I don't know. xcode's build logic is quite frustrating if you are doing anything at all non-simple. Much prefer GNU make if I have to do anything complex. Wouldn't have thought STL would qualify :)

**Comment by rsms** [comment]
Nowadays Xcode defaults to the clang version of libc++ — there's an Xcode setting to have the compiler use libstdc++ (GNU) instead of the "new" libc++. You might try to change that and see if that helps your compiler to find the STL headers.
