### ISSUE TITLE
Browser window minimize/maximize/close buttons don't work properly

### ISSUE THREAD

**Issue by houbysoft** [rsms/chromium-tabs#16]
I can reproduce this with the example project given in the source code distribution. Latest OS X (10.8.4), latest Xcode (4.6.3).

The window shows up fine, but the minimize/maximize/close buttons don't show the X – + when you mouse over, as they are supposed to in all OS X windows.

It looks very strange and feels as though it's frozen, even though the buttons work fine (and it does show the X – + when you click a button, just mouse over seems broken).

Is this a known issue? How can it be fixed?

**Comment by elklein** [comment]
Are you still seeing this? At least with the forks for myself or dparnell (both ARC based) I don't think you should be seeing this. At the very least, I'm not seeing this issue, and I'm running on 10.9.1 with xcode 5.0.2 using the source from https://github.com/elklein/chromium-tabs.

**Comment by rsms** [comment]
I just merged in @elklein's changes into master. @houbysoft, LMK if you're still having issues.
