### ISSUE TITLE
vertically center stoplights

### ISSUE THREAD

**Issue by billculp** [rsms/chromium-tabs#18]
See INAppStoreWindow.

**Comment by rsms** [comment]
Explicitly decided not to have them vertically centered. The day where the majority of my on-screen windows have the stoplights centered, it will start making sense to center them on your own products. It's simply cognitively inefficient.

**Comment by billculp** [comment]
Perhaps your screenshot is out of date taken from Lion or Snow Leopard but the stoplights in the screenshot are not anything close to what they are now in OS X.  My suggestion was only related to _if_ you are self drawing the stoplights then you should make that malleable otherwise this is a frozen component.

However if its just an out of date screenshot showing overblown stoplights on the bleeding edge of the window which is not where OS X places them, then I can agree that letting the OS determine the location is OK.

But there is a missing concept in this discussion... The only reason your project exists is to "draw over" or self draw the window frame.  So why wouldnt you (since your in there anyway) make it fit with the stoplights?  Again see INAppStoreWindow.

I get the feeling you are done with this project so I wont bug you about it Ill just do it myself.
