### ISSUE TITLE
Will be crashed under x86 and no-ARC?

### ISSUE THREAD

**Issue by keepwn** [rsms/chromium-tabs#21]
Hello.
I wanna call your framework in monomac, but it requires under x86.
So i modified chromium-tabs framework to x86 and turn ARC off (ARC not supports x86), but the program will be crashed when mouse hover on tab, like this:
![crash](https://cloud.githubusercontent.com/assets/7532281/4826617/379651b0-5f72-11e4-82c1-18d3f5d584c2.PNG)

Could you help me?

**Comment by elklein** [comment]
Take this with a grain of salt, but the conversion to ARC was a pretty major thing. I think it's possible that the ARC version just won't work without a LOT of debugging and work in a non-ARC environment. I'd take a look for other forks of the project that are non-ARC (there are several IIRC) and see if you can use one of those. That might be the easiest way to make progress quickly.

**Comment by keepwn** [comment]
So thanks.I had planned to debug it by myself, but bite off more than one can chew, I'm not good at objective-c programming.

**Comment by rsms** [comment]
Project no longer maintained.
