### ISSUE TITLE
OS 10.10 Issues

### ISSUE THREAD

**Issue by deviks** [rsms/chromium-tabs#23]
Adding the framework throws a fatal error:

dyld`dyld_fatal_error:
0x7fff5fc01074:  int3  
0x7fff5fc01075:  nop    

I'd like to use your method to implement tabs in CEF. When I compile the code on OS 10.10 I am seeing the following error (along with deprecations for isa, convertScreentoBase, convertBasetoScreen):

CTTabStripController.m:
ARC Semantic Issue:
[[[view animationForKey:@"frameOrigin"] delegate] invalidate];

How would you recommend I go about fixing this? (I'm new to Objective C, CEF etc.)

Thanks.

![chromiumtabserrs](https://cloud.githubusercontent.com/assets/11195437/6590384/5ef9330a-c785-11e4-9647-fa83b0b43033.png)

Thanks

**Comment by rsms** [comment]
Wow. I didn't think anyone was using chromium-tabs anymore. It's based on a really really old version of Chromium. I'm afraid you're on your own here my friend. I am not maintaining this old project anymore.
