### ISSUE TITLE
Chromium-tabs are crashing if garbage collection is enabled

### ISSUE THREAD

**Issue by jarek-foksa** [rsms/chromium-tabs#8]
Is is possible to use this framework in app that uses garbage collection? My simple app started crashing after I have added Chromium-tabs and enabled garbage collection in build options.

**Comment by rsms** [comment]
As long as you link dynamically to the framework (and of course build it w/o GC), then use supported (not "required") GC, it should work. However, if you're building something new I highly recommend using ARC instead.

**Comment by jarek-foksa** [comment]
It looks like latest XCode 4.2 beta comes with ARC compiler, I will give it a try. Thanks for help!
